apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: izziee/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MAILJET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailjet-api-key
                  key: MAILJET_API_KEY
            - name: MAILJET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailjet-api-secret
                  key: MAILJET_SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

