name: tests-auth

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci